"""baseline: match existing SQLAlchemy models

Revision ID: 0512b890af99
Revises: 
Create Date: 2026-08-24 03:14:23.898692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '0512b890af99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'is_default',
               existing_type=mssql.BIT(),
               nullable=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_foreign_key(None, 'holdings', 'portfolios', ['portfolio_id'], ['id'])
    op.alter_column('users', 'email_alerts_enabled',
               existing_type=mssql.BIT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_alerts_enabled',
               existing_type=mssql.BIT(),
               nullable=True)
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.alter_column('assets', 'is_default',
               existing_type=mssql.BIT(),
               nullable=True)
    # ### end Alembic commands ###
