"""add 2fa, sessions, audit log, portfolio benchmark/share fields

Revision ID: 9ef7c625bc0c
Revises: 0512b890af99
Create Date: 2026-08-24 03:52:28.524392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '9ef7c625bc0c'
down_revision: Union[str, None] = '0512b890af99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.alter_column('assets', 'is_default',
               existing_type=mssql.BIT(),
               nullable=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_foreign_key(None, 'holdings', 'portfolios', ['portfolio_id'], ['id'])
    op.add_column('portfolios', sa.Column('benchmark_symbol', sa.String(length=20), nullable=True))
    op.add_column('portfolios', sa.Column('benchmark_label', sa.Unicode(length=100), nullable=True))
    op.add_column('portfolios', sa.Column('share_token', sa.String(length=64), nullable=True))
    # MSSQL's plain unique index treats multiple NULLs as duplicates (unlike most
    # dialects) — a filtered index (only indexing non-NULL values) is required so
    # every not-yet-shared portfolio (share_token IS NULL) doesn't collide.
    op.create_index(
        op.f('ix_portfolios_share_token'),
        'portfolios',
        ['share_token'],
        unique=True,
        mssql_where=sa.text('share_token IS NOT NULL'),
    )
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    # NOT NULL columns on an already-populated table need a server default so existing
    # rows backfill instead of failing the ALTER TABLE outright.
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('base_currency', sa.String(length=6), nullable=False, server_default='TRY'))
    op.alter_column('users', 'email_alerts_enabled',
               existing_type=mssql.BIT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_alerts_enabled',
               existing_type=mssql.BIT(),
               nullable=True)
    op.drop_column('users', 'base_currency')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_index(op.f('ix_portfolios_share_token'), table_name='portfolios')
    op.drop_column('portfolios', 'share_token')
    op.drop_column('portfolios', 'benchmark_label')
    op.drop_column('portfolios', 'benchmark_symbol')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.alter_column('assets', 'is_default',
               existing_type=mssql.BIT(),
               nullable=True)
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
