"""add digest frequency to users

Revision ID: f085766d612d
Revises: 9ef7c625bc0c
Create Date: 2026-08-24 15:23:17.755586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f085766d612d'
down_revision: Union[str, None] = '9ef7c625bc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: a NOT NULL column added to a
    # table that already has rows needs a server_default so MSSQL can backfill existing
    # rows, matching the model's own default="off". ###
    op.add_column('users', sa.Column('digest_frequency', sa.String(length=10), nullable=False, server_default='off'))
    op.add_column('users', sa.Column('last_digest_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_digest_sent_at')
    op.drop_column('users', 'digest_frequency')
    # ### end Alembic commands ###
